### PR TITLE
fix: parsing code issue + add more logs

### LINKED ISSUE #137: Fix bug on skills-matrix

### PR DESCRIPTION
**Pull request by nherment**
Fixes #137

### CODE REVIEW

File: functions/createReview/astParsing/rules/no_loop_await.js [hunk 1]
```diff
@@ -31,6 +31,8 @@ function isCalleeFunction(node, callFunctionName) {
 
 export function isArrayFunctionCall(node, functionName) {
   return (
+    !!node &&
+    !!node.type &&
```
Comment (nherment) [inline functions/createReview/astParsing/rules/no_loop_await.js:35]: This is the fix

**Review by simoneb — APPROVED** [review]
